module PopplerFFI
  class Permissions
    POPPLER_PERMISSIONS_OK_TO_PRINT = 1 << 0
    POPPLER_PERMISSIONS_OK_TO_MODIFY = 1 << 1
    POPPLER_PERMISSIONS_OK_TO_COPY = 1 << 2
    POPPLER_PERMISSIONS_OK_TO_ADD_NOTES = 1 << 3
    POPPLER_PERMISSIONS_OK_TO_FILL_FORM = 1 << 4
    POPPLER_PERMISSIONS_OK_TO_EXTRACT_CONTENTS = 1 << 5
    POPPLER_PERMISSIONS_OK_TO_ASSEMBLE = 1 << 6
    POPPLER_PERMISSIONS_OK_TO_PRINT_HIGH_RESOLUTION = 1 << 7
    POPPLER_PERMISSIONS_FULL = (POPPLER_PERMISSIONS_OK_TO_PRINT | POPPLER_PERMISSIONS_OK_TO_MODIFY | POPPLER_PERMISSIONS_OK_TO_COPY | POPPLER_PERMISSIONS_OK_TO_ADD_NOTES | POPPLER_PERMISSIONS_OK_TO_FILL_FORM | POPPLER_PERMISSIONS_OK_TO_EXTRACT_CONTENTS | POPPLER_PERMISSIONS_OK_TO_ASSEMBLE | POPPLER_PERMISSIONS_OK_TO_PRINT_HIGH_RESOLUTION)

    def initialize(permissions_int)
      @permissions_int = permissions_int
    end

    # TODO: implement each permission methods
  end
end
