language: ruby
rvm:
  - 2.3.0
os:
  - linux
  #- osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get -qq update                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -y libpoppler-glib-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install poppler; fi
  - gem install bundler -v 1.11.2

script: bundle exec rspec spec
