language: ruby
sudo: required
dist: trusty
cache:
  - rvm
  - bundler
rvm:
  - 2.3.0
os:
  - linux
  #- osx

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpoppler-glib-dev poppler-data ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ${TRAVIS_BUILD_DIR}/build_poppler.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install poppler; fi
  - gem install bundler -v 1.11.2

script: bundle exec rspec spec
