language: ruby
rvm:
  - 2.2.3
  - 2.2.4
  - 2.3.0
os:
  - linux
  - osx

addons:
  apt:
    - poppler-utils
    - poppler-data

before_install:
  - gem install bundler -v 1.11.2
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install poppler; fi

script: bundle exec rspec spec
