language: ruby
rvm:
  - 2.3.0
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libpoppler-glib-dev
      - poppler-utils

before_install:
  - rvm get latest
  - gem install bundler -v 1.11.2
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install poppler; fi

script: bundle exec rspec spec
