language: ruby
cache:
  - rvm
  - bundler
rvm:
  - 2.3.0
os:
  - linux
  #- osx

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ${TRAVIS_BUILD_DIR}/build_poppler.sh  ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install poppler; fi
  - gem install bundler -v 1.11.2

script: bundle exec rspec spec
