language: ruby
cache:
  - rvm
  - bundler
rvm:
  - 2.3.0
os:
  - linux
  #- osx

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-mate-dev/xenial-mate  ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update   ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get upgrade  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpoppler-glib-dev  ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install poppler; fi
  - gem install bundler -v 1.11.2

script: bundle exec rspec spec
